version: "2"
services:
  master:
    build: .
    image: distributed
    ports:
      - "8000:8000"
    command: "python main-server.py -s http://secondary1:5000/ -s http://secondary2:5000/"

  secondary1:
    depends_on:
      - master
    image: distributed
    ports:
      - "8001:8000" # public port
    command: "python secondary-server.py"
  secondary2:
    depends_on:
      - master
    image: distributed
    ports:
      - "8002:8000" # public port
    command: "python secondary-server.py"